name = "cellproto-signaling"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]
